# TODO - Same with immortal's default
{
  imports = [
    ./../../common/global/acme/wc-dns-egor.nix
    ./../../common/global/acme/wc-egor.nix
    ./../../common/global/backup/borg.nix
    ./../../common/global/backup/restic.nix
    ./../../common/global/cleanup.nix
    ./../../common/global/hardening.nix
    ./../../common/optional/adguard/default.nix
    ./../../common/optional/adguard/unbound.nix
    ./../../common/optional/cfdyndns.nix
    ./../../common/optional/containers/simplex.nix
    ./../../common/optional/crypto/monero-node.nix
    ./../../common/optional/forgejo.nix
    ./../../common/optional/grafana.nix
    ./../../common/optional/headscale/default.nix
    ./../../common/optional/jellyfin/default.nix
    ./../../common/optional/jellyseer.nix
    ./../../common/optional/mailserver.nix
    ./../../common/optional/nextcloud.nix
    ./../../common/optional/nginx/authelia.nix
    ./../../common/optional/nginx/default.nix
    ./../../common/optional/ntfy-sh/default.nix
    ./../../common/optional/paperless/default.nix
    ./../../common/optional/photoprism/default.nix
    ./../../common/optional/searx-ng/default.nix
    ./../../common/optional/tpm.nix
    ./../../common/optional/transmission/default.nix
    ./../../common/optional/vaultwarden/default.nix
    ./asteriks.nix
    #./impermanence.nix
    ./syncthing.nix
    #./tailscale.nix
  ];
}
